import { useEffect, useState } from 'react';
import { AxiosError } from 'axios';
import api from '@/api/axios';
import { BackendUser, TelegramUser } from '@/types';

const useTelegramUser = () => {
  const [user, setUser] = useState<BackendUser | null>(null);

  useEffect(() => {
    const fetchOrCreateUser = async () => {
      const telegramUser = (window as any)?.Telegram?.WebApp?.initDataUnsafe?.user as TelegramUser | undefined;

      // Fallback: create user with autogenerated ID if telegram ID is missing
      const generatedId = crypto.randomUUID();

      const userId = telegramUser?.id || generatedId;

      // Check if user already exists in localStorage
      const storedUser = localStorage.getItem('telegramUser');
      if (storedUser) {
        setUser(JSON.parse(storedUser));
        return;
      }

      try {
        // Try to fetch user only if Telegram ID exists
        if (telegramUser?.id) {
          const { data } = await api.get<BackendUser>(`users/findbyTelegramId/${telegramUser.id}`);
          localStorage.setItem('telegramUser', JSON.stringify(data));
          setUser(data);
          console.log('Fetched existing user:', data);
          return;
        }

        throw new Error('No Telegram ID, fallback to new user creation.');
      } catch (error) {
        const err = error as AxiosError<{ message: string }>;

        if (
          err?.response?.data?.message === 'User not found' ||
          err.message === 'No Telegram ID, fallback to new user creation.'
        ) {
          const newUserPayload: TelegramUser = {
            ...telegramUser,
            id: userId,
          };

          try {
            const { data: createdUser } = await api.post<BackendUser>('users/create', newUserPayload);
            localStorage.setItem('telegramUser', JSON.stringify(createdUser));
            setUser(createdUser);
            console.log('Created new user:', createdUser);
          } catch (creationError) {
            console.error('Error creating new user:', creationError);
          }
        } else {
          console.error('Unexpected error during fetch/create:', err.message);
        }
      }
    };

    fetchOrCreateUser();
  }, []);

  return user;
};

export default useTelegramUser;
