name: CI/CD to DigitalOcean
on:
  push:
    branches: [dev] # Trigger the workflow on push to the dev branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Deploy to DigitalOcean Droplet via SSH with password
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 68.183.216.158
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd Lije-care-mini-app/dev
            git stash # Stash any local changes to avoid conflicts
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git pull
            npm install
            npm run build






